# Generated by Django 6.0.2 on 2026-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее уведомление'),
        ),
    ]
